name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug: Print Docker credentials (check in logs)
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}" | sha256sum  # Mask password by hashing it
        continue-on-error: true  # Ensure the job continues even if this step fails

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Reference the Docker username secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Reference the Docker password secret

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: |
          IMAGE_TAG=my-image-name:${{ github.sha }}  # Use commit hash for a unique tag
          docker build . --file Dockerfile --tag $IMAGE_TAG --build-arg BUILDKIT_INLINE_CACHE=1
          echo "Built image with tag: $IMAGE_TAG"
      
      - name: Push Docker Image to DockerHub
        run: |
          IMAGE_TAG=my-image-name:${{ github.sha }}  # Use the same tag for pushing
          docker push $IMAGE_TAG
