name: ZAP Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd docker.io || true
          curl -fsSL https://get.docker.com | sudo sh
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Pull ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Run ZAP Scan
        run: |
          mkdir -p zap-session
          docker run --rm -v $(pwd)/zap-session:/zap/wrk/:rw \
            -p 8080:8080 zaproxy/zap-stable zap-full-scan.py -t https://security123team.github.io/test/ \
            -r /zap/wrk/zap-report.html || true  # Ensures workflow doesn't fail on warnings

      - name: Debug: Check if Report Exists
        run: ls -R zap-session

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-session/zap-report.html
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
