name: ZAP Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd docker.io || true
          curl -fsSL https://get.docker.com | sudo sh
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Pull ZAP Docker Image
        run: docker pull zaproxy/zap-stable

      - name: Run ZAP Scan
        run: |
          mkdir -p zap-session
          # Run ZAP scan and output the report to a known location
          docker run --rm -v $(pwd)/zap-session:/zap/wrk/:rw \
            -p 8080:8080 zaproxy/zap-stable zap-full-scan.py -t https://security123team.github.io/test/ -r /zap/wrk/zap-session/zap_report.html || true  # Output report to zap_report.html

      - name: List files in zap-session
        run: ls -l zap-session  # List all the files in zap-session to check if the report was created

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-session/zap-report.html  # Update path to match the generated report
          if-no-files-found: warn  # Keep warning in case the file doesn't exist
          compression-level: 6
          overwrite: false
          include-hidden-files: false
