name: ZAP Security Scan
on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "https://bitscrunch.com/"
          - "https://app.bitscrunch.com/"  # new domain
    name: Scan ${{ matrix.target }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Ignore Rules File
        run: |
          mkdir -p .zap
          echo "10035    # Strict-Transport-Security Disabled" > .zap/ignore-rules.tsv
          echo "10038    # Content Security Policy (CSP) Header Not Set" >> .zap/ignore-rules.tsv
          echo "10096    # Timestamp Disclosure - Unix" >> .zap/ignore-rules.tsv
          echo "40025    # Proxy Disclosure" >> .zap/ignore-rules.tsv
          cat .zap/ignore-rules.tsv  # Verify contents of the rules file

      - name: Extract Domain Name
        id: extract_domain
        run: |
          DOMAIN=$(echo "${{ matrix.target }}" | sed -E 's#https?://##' | sed 's#/$##')
          echo "Extracted Domain: $DOMAIN"
          echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV

      - name: List Files in Working Directory
        run: |
          echo "Listing all files in the current working directory..."
          ls -lah

      - name: Set Permissions for .zap Directory and Rules File
        run: |
          chmod -R 755 .zap  # Set read/write/execute permissions for the directory
          chmod 644 .zap/ignore-rules.tsv  # Ensure the file is readable
          ls -lah .zap  # List files to verify permissions

      - name: Check if Ignore Rules File Exists
        run: |
          if [ ! -f .zap/ignore-rules.tsv ]; then
            echo "Error: .zap/ignore-rules.tsv file does not exist!"
            exit 1
          fi
          echo ".zap/ignore-rules.tsv file exists."

      - name: Delete Old Report (If Exists)
        run: |
          if [ -f zap-reports/zap_report_${{ env.DOMAIN }}.html ]; then
            echo "Deleting old report for ${{ env.DOMAIN }}..."
            rm -f zap-reports/zap_report_${{ env.DOMAIN }}.html
          fi

      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{
